HW1
mahkons/Software-design-course-HSE2020 pull request #2
Opened 2020-01-27 19:56 UTC by mahkons

2020-02-09 19:02 UTC, yurii-litvinov requested changes
С кавычками что-то не то:
```
->x=1
->echo "'$x'"
'
```
Ожидалось '1'

И не показывает поток ошибок. Попробуйте `git ololo`.

2020-02-09 19:02 UTC, yurii-litvinov commented on CLI/lib/googletest/.clang-format
> +# Run manually to reformat a file:
Более каноничноЪ было бы качать Google Test прямо во время билда, как тут рекомендуют: https://github.com/google/googletest/blob/master/googletest/README.md. git submodule тоже был бы разумной альтернативой. Иначе получилось 114 000 строк в диффе и если бы мы захотели посчитать какие-то метрики по Вашему репозиторию, результаты получились бы не очень.

2020-02-09 19:02 UTC, yurii-litvinov commented on CLI/inc/application.h
> +    /* Command line interface
Лучше Doxygen-совместимые комментарии, с `/**`

2020-02-09 19:02 UTC, yurii-litvinov commented on CLI/inc/commands/assignment_command.h
> +            : env_(env), variable_name_(variable_name), variable_value_(variable_value) {};
В C++ нынче принято строки (и векторы, ниже) по значению передавать, или Вы поленились по константной ссылке?

2020-02-09 19:02 UTC, yurii-litvinov commented on CLI/inc/commands/command_factory.h
> +    using factoryResult = Result<std::shared_ptr<Command>, std::string>;
Лучше договориться среди себя, что все типы всегда называются в CamelCase, даже синонимы

2020-02-09 19:02 UTC, yurii-litvinov commented on CLI/inc/parser/token.h
> +        std::string value;
Неконстантное паблик-поле? Я бы тут всё, что можно, сделал немутабельным.

2020-02-10 14:04 UTC, mahkons commented
> С кавычками что-то не то:
> 
> ```
> ->x=1
> ->echo "'$x'"
> '
> ```
> 
> Ожидалось '1'
> 
> И не показывает поток ошибок. Попробуйте `git ololo`.

он воспринимает внутреннюю кавычку как обычный символ и ищет переменную x'
это не ожидаемое поведение?

2020-02-10 14:39 UTC, mahkons commented on CLI/inc/parser/token.h
> +        std::string value;
fixed
здесь и много где еще

2020-02-10 14:39 UTC, mahkons commented on CLI/inc/commands/command_factory.h
> +    using factoryResult = Result<std::shared_ptr<Command>, std::string>;
fixed

2020-02-10 14:39 UTC, mahkons commented on CLI/inc/commands/assignment_command.h
> +            : env_(env), variable_name_(variable_name), variable_value_(variable_value) {};
fixed
здесь и много где еще

2020-02-10 15:11 UTC, mahkons commented on CLI/lib/googletest/.clang-format
> +# Run manually to reformat a file:
Выглядит ужасно, это правда
fixed

2020-02-10 15:11 UTC, mahkons commented on CLI/inc/application.h
> +    /* Command line interface
обновлено

2020-03-09 13:15 UTC, yurii-litvinov approved these changes
>он воспринимает внутреннюю кавычку как обычный символ и ищет переменную x'
>это возможное ожидаемое поведение?

Вообще нет, в имени переменной могут быть буквы, цифры и подчёркивания (может, что-то ещё, но не кавычки, доллары и т.д.). Но это единственный оставшийся недостаток, так что зачтена

2020-03-09 13:15 UTC, yurii-litvinov commented on CLI/inc/commands/command_factory.h
> +        FactoryResult parse_command(std::vector<std::string> args) const;
И это надо бы по ссылке передавать

2020-03-22 10:15 UTC, merged